server:
  port: 8888
spring:
  application:
    name: config
  profiles:
    active: dev
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/anakinf_admin/SpringCloudStudy.git #配置git仓库地址
          searchPaths: 第09课/config #配置仓库路径
          username: anakin.s@163.com #访问git仓库的用户名
          password: Anakin!123 #访问git仓库的用户密码
      label: master #配置仓库的分支
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin
    virtualHost: /
    publisherConfirms: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
    endpoints:
        web:
            exposure:
                include: refresh,health,info,bus-refresh